# seed
seed: 1

# dataset generator
env_name: "Pendulum-v1"
# frame_dim1: 84
# frame_dim2: 84
num_episodes: {0: 20, 1: 5}   # num_episode per level of fidelity

# training hyperparameters
batch_size: 50
max_epoch: 500

rho: 1 

training: true
# plotting: false
# num_samples_plot: 200

# learning rate
lr: 3e-4
lr_gp: 1e-2
#lr_gp_var: 1e-2
#lr_gp_lik: 1e-2
reg_coef: 1e-2
#k1: 0.9  # coefficient-recon-loss
#k2: 0.9  # coefficient-fwd-kl-loss
grid_size: 32

# build model
latent_dim: 50
act_dim: 1
state_dim: 3
obs_dim_1: {0: 42, 1: 84}
obs_dim_2: {0: 42, 1: 84}
obs_dim_3: 6
h_dim: 256
out_dim: {128: 57, 84: 35, 64: 25, 42: 14, 24: 5}

# experiment and model type
exp: "Pendulum"
mtype: "DKL"
training_dataset: {0: "pendulum_train_0.pkl", 1: "pendulum_train_1.pkl"}
testing_dataset: {0: "pendulum_test_0.pkl", 1: "pendulum_test_1.pkl"}

log_interval: 50

jitter: 1e-8

# weights
weights_filename: ["MFDKL_LF_42_2024-03-04_19h-22m-01s",
                   "MFDKL_HF_42-84_2024-03-04_20h-18m-22s"]
