# seed
seed: 2

# dataset generator
env_name: "Pendulum-v1"
# frame_dim1: 84
# frame_dim2: 84
num_episodes: {0: 10, 1: 3}   # num_episode per level of fidelity

# training hyperparameters
batch_size: 50
max_epoch: 100

rho: 1 

training: true
# plotting: false
# num_samples_plot: 200

# learning rate
lr: 1e-4
lr_gp: 1e-2
lr_gp_var: 1e-2
lr_gp_lik: 1e-2
reg_coef: 1e-2
k1: 1.0  # coefficient-recon-loss
k2: 1.0  # coefficient-fwd-kl-loss
grid_size: 32

# build model
latent_dim: 20
act_dim: 1
state_dim: 3
obs_dim_1: {0: 42, 1: 84}
obs_dim_2: {0: 42, 1: 84}
obs_dim_3: 6
h_dim: 256
out_dim: {128: 57, 84: 35, 64: 25, 42: 14, 24: 5}

# experiment and model type
exp: "Pendulum"
mtype: "DKL"
training_dataset: {0: "pendulum_train_0.pkl", 1: "pendulum_train_1.pkl"}
testing_dataset: {0: "pendulum_test_0.pkl", 1: "pendulum_test_1.pkl"}

log_interval: 50

jitter: 1e-8

# weights
weights_filename: "MFDKL_84-3_84-1_2023-12-12_19h-38m-08s"
