# seed
seed: 2

# dataset generator
env_name: "Pendulum-v1"
# frame_dim1: 84
# frame_dim2: 84
num_episodes: {0: 10, 1: 2}   # num_episode per level of fidelity
jump: {0: 5, 1: 1}            # jump in render per level of fidelity

# training hyperparameters
batch_size: 50
max_epoch: 100

training: true
plotting: false
num_samples_plot: 200

# learning rate
lr: 1e-4
lr_gp: 1e-2
lr_gp_var: 1e-2
lr_gp_lik: 1e-2
reg_coef: 1e-2
k1: 1.0  # coefficient-recon-loss
k2: 1.0  # coefficient-fwd-kl-loss
grid_size: 32

# build model
latent_dim: 20
act_dim: 1
state_dim: 3
obs_dim_1: 84
obs_dim_2: 84
obs_dim_3: 6
h_dim: 256
out_dim: {128: 57, 84: 35, 64: 25, 42: 14, 24: 5}

# noise level on observations
noise_level: 0.0

# noise level on dynamics (actions)
noise_level_act: 0.0

# experiment and model type
exp: "Pendulum"
mtype: "DKL"
training_dataset: "pendulum_train.pkl"
testing_dataset: "pendulum_test.pkl"

log_interval: 50

jitter: 1e-8

# weights
weights_filename: "DKL_Model_128_2023-11-03_15h-39m-42s.pth"
