# Seed
seed: 1

# Dataset generator
env_name: "MountainCarContinuous"  # Available: Pendulum, Acrobot, MountainCarContinuous, reaction-diffusion, diffusion-advection

## Gym environment parameters
num_episodes: {0: 150, 1: 50}
num_episodes_test: {0: 3, 1: 3}
crop: [{'portion': 1, 'pos': 4}, {'portion': 1, 'pos': 4}]
occlusion: [{'portion': 0, 'pos': 4}, {'portion': 0, 'pos': 4}]

## PDE environment parameters
d: {0: 0.05, 1: 0.05} 
mu: {0: [0.5, 0.75, 1, 0.6, 1.15, 1.375], 1: [0.5, 0.75, 1]}  # please, insert the common values first  
mu_test: [0.5, 1, 0.6, 1.15]
T: {0: 80, 1: 40}
T_test: 10
dt: 0.1
L: 20
n: {0: 32, 1: 100}  # grid size, should be the same as obs_dim_1 and obs_dim_2

# d: {0: 0.001, 1: 0.001}
# mu: {0: [1.5, 2.5, 3.5, 4.5], 1: [1.5, 2.5]}
# mu_test: [1.5, 2.5, 3.5]
# T: {0: 30, 1: 10}
# T_test: 5
# dt: 0.01
# L: 5
# n: {0: 32, 1: 100}  # grid size, should be the same as obs_dim_1 and obs_dim_2


# Training hyperparameters
batch_size: 20
max_epoch: 1

rho: 1 

training: true

# Learning rate
lr: 3e-4
lr_gp: 1e-2
lr_gp_lik: 1e-2
lr_gp_var: 1e-2
reg_coef: 1e-2
k1: 0.9  # coefficient-recon-loss
k2: 0.9  # coefficient-fwd-kl-loss
grid_size: 32

# build model
latent_dim: 20
obs_dim_1: {0: 32, 1: 84}
obs_dim_2: {0: 32, 1: 84}
obs_dim_3: 6
h_dim: 256

# experiment and model type
training_dataset: {0: "data_train_0.pkl", 1: "data_train_1.pkl"}
testing_dataset: {0: "data_test_0.pkl", 1: "data_test_1.pkl"}
log_interval: 50

jitter: 1e-6

# weights
results_folder: "2024-08-10_17h-39m-38s"
weights_filename: ["MFDKL_dyn_level0_32_2024-08-10_17h-39m-39s",
                   "MFDKL_dyn_level1_100_2024-08-10_17h-39m-41s"]
ID: 2


